#!/usr/bin/env bash

# To use this script, pipe the contents of a MD file into it.
# It will output that content reformatted for Readme.

# Examples:
# Reformat the contents of the clipboard
# xclip -o | ./pipe-convert-for-readme | xclip -selection clipboard
#
# Reformat a file and write it to a new file
# cat ../_includes/devdoc/guide_block_chain.md | ./pipe-convert-for-readme > ../_readme/guide_block_chain.md

perl -0777 \
-pe "s/\{% comment %\}[^{]+\{% endcomment %\}//gs;" \
-pe "s/\[([^]]+).+\.term\}/<<glossary:\1>>/g;" \
-pe "s/<<([^>]+)\n([^>]+)>>/<<\1 \2>>/gs;" \
-pe "s!/img/dev!https://dash-docs.github.io/img/dev!g;" \
-pe "s/{[^}]+}//g;" \
-pe "s/\n\n+/\n\n/g;"
